### ISSUE TITLE
Block names with brackets aren't converted

### ISSUE THREAD

**Issue by umverteiler** [ebroecker/a2l-xml#1]
Hi,

first of all: Great script - really helpful for our use case 👍 

Testing it with several a2l files I noticed a problem with MEASUREMENTS blocks that are using names with brackets. Probably the problem occurs with any kind of block that uses brackets in it's name?

Example: Sb177_Div_T **[0]**
```
    /begin MEASUREMENT Sb177_Div_T[0] ""
      FLOAT32_IEEE VOID_SCALING 1 100 -2.5 12.4
      BYTE_ORDER MSB_LAST
      ECU_ADDRESS 0x60012514
      ECU_ADDRESS_EXTENSION 0x0
      FORMAT "%12.6"
      SYMBOL_LINK "Sb177_Div_T" 0
    /end MEASUREMENT
```

At first I thought names with brackets aren't valid - so your script is 'right' - but then I checked the ASAP / A2L specification which says:

> Identifiers are random names which may contain characters A through Z, 
> a through z, underscore (_), numerals 0 through 9, points (.) and brackets ([, ]) . 
> However, the following limitations apply: the first character must be a letter or an underscore,
> brackets must occur in pairs at the end of a partial string and must contain a number 
> or an alphabetic string (description of the index of an array element).

My knowledge in Python is unfortunately very poor, otherwise I'd like to extend your script to handle this kind of names. But maybe you could take a look? I'm willing to help in any kind (testing it or providing more examples).

Currently the brackets are simply ignored, but this results - in our case - into MEASUREMENT blocks of the same name.

**Comment by ebroecker** [comment]
Hi,
congratulations. You are the first one, who uses this script and gave feedback!

I'll have a look on it

**Comment by ebroecker** [comment]
I did a little work about it. Feel free to test it!

Eduard

**Comment by umverteiler** [comment]
Okay, this help for nearly all errors during the conversion, but I still got some errors in regard to brackets in identifiers of FUNCTIONS and their LOC_MEASUREMENTs.

Simple Example from the ASAP Specification:

```
/begin FUNCTION.  ID_ADJUSTM /* name */ "function group idling adjustment" 
   /begin DEF_CHARACTERISTIC INJECTION_CURVE
   /end DEF_CHARACTERISTIC 
   /begin REF_CHARACTERISTIC FACTOR_1
   /end REF_CHARACTERISTIC 
   /begin IN_MEASUREMENT WHEEL_REVOLUTIONS ENGINE_SPEED
   /end IN_MEASUREMENT 
   /begin OUT_MEASUREMENT OK_FLAG SENSOR_FLAG
   /end OUT_MEASUREMENT 
   /begin LOC_MEASUREMENT LOOP_COUNTER TEMPORARY_1 MY_MEASUREMENT[0]
   /end LOC_MEASUREMENT 
   /begin SUB_FUNCTION ID_ADJUSTM_SUB
   /end SUB_FUNCTION 
/end FUNCTION
```

Then inside LOC_MEASUREMENT we're using the MEASUREMENT name with the brackets (that was / is fixed by your latest commit).

The thing is, our own a2l file only covers "so much", that their might be some more cases were the identifier of a block descriptor could contain a pair of brackets. So the question is, if there's a way to define the overall handling / format of identifier in your parser. Otherwise we might fix this for now, but will probably step over it again using a different a2l file (I will certainly test it with all a2l files that are available to us).

**Comment by ebroecker** [comment]
I'll do some further work for better bracket support this evening.

**Comment by umverteiler** [comment]
This seems to work perfectly - we get no more errors during the conversion. Thanks a lot!

**Comment by ebroecker** [comment]
Thanks die the Feedback
